import { Inter } from "next/font/google";
import Link from "next/link";
import Image from "next/image";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Call from "@/public/Images/call-fixed.svg";

// ---> Css
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Generators",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                {children}
                <Footer />
                <Link
                    href="tel:+998900013666"
                    className="hidden sm:block fixed bottom-14 !right-[100px] w-[60px] h-[60px]  z-50 animate-bounce"
                >
                    <Image src={Call} width={60} height={60} alt="call" />
                </Link>
            </body>
        </html>
    );
}
